### ISSUE TITLE
Examples/Guides

### ISSUE THREAD

**Issue by larsbuch** [azist/azos#159]
Is there examples/guides ready? Are the older NFX useful? I am especially looking for Wave, Cache and Pile (in that order). I am especially evaluation framework for use in workflows of micro/nano services strung together in configuration which might be doable in Wave. I need a good way to cache data with a readable timeout for short term data and caching business data for longer time. Pile (and thus also cache) I would like to experiment with inplace object reading in Pile as I do not see a problem in minor modification of business objects for the framework it is used in.

**Comment by zhabis** [comment]
The guides is a constant work in progress, you can use older NFX stuff as a guideline yes, but use Azos.

Not sure how you are planning to benefit from Wave alone, the Wave makes sense if you use the whole stack, otherwise you can use standard .net asp.core (if you like it).

As far as pile+cache, it would pay-off if you are keeping multi-million objects in memory for a long (minutes) time. Keep in mind, if you hold 100K business objects each having an array of 10 smaller objects, you are really keeping 100,000 objects already. If you have string fields, that all adds up. It is very easy to get into multi-million range and start seeing GC stalls while dealing only with 100K-200K of business entities.

**Comment by zhabis** [comment]
@larsbuch will need to know a bit more details about your use case to suggest a pattern/what to use and how
