### ISSUE TITLE
Is it possible to TAG a log stream, say from web so that user-induced errors (like 404, 403) do not get logged on a regular stream

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#244]
Maybe this should be done only in web error filter (when logging is turned on), then add a filter pattern on log sink;
for appcomponets we can override ComponentLogTopic

**Comment by zhabis** [comment]
All output from WAVE is tagged with "WAVE" topic in `WorkCOntext.Log()` which `ErrorFilter` calls, the problem is that complex log Sink filter pattern is disabled now because filter expression has been not fully refactored yet due to dynamic code compiler anavailability. This has to wait until sink custom filtering gets resolved, probably using `FilterExpression` as injectable entity

**Comment by zhabis** [comment]
Re # 249

**Comment by zhabis** [comment]
WIP c2c272c

**Comment by zhabis** [comment]
Use `Sink.Filter`
