### ISSUE TITLE
We need appliance-mode MinIdp/MongoDb provider with built-in replication of changes. Changes applied to one instance cascade into others

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#348]

**Comment by zhabis** [comment]
Since MinIdp outlines contract ONLY for CONSUMPTION (reading) of security catalog data, we can design whatever "management"/data change  mechanisms we like. We can make them Mongo-specific.
The data replication can be very simple, because this is not a general-purpose database and its data collections have very specific purpose. @JohnPKosh RFC

**Comment by JohnPKosh** [comment]
I was arriving at a similar conclusion this morning, MinIdp does not have to know how management is implemented.  Should we handle commands through a single configured primary with failover then cascade to read segregated nodes to start then move future state to something more along the lines of Raft Concensus Algoritm (https://raft.github.io/ or https://medium.com/@amangoeliitb/raft-consensus-algorithm-d93e7ee22b12) for actual implementation?
