### ISSUE TITLE
Api doc uses GUID for type id which is different in clustered environment, consequently traffic may not be balanced between the two nodes.

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#372]
Solution: use stable type IDs derived from metadata token only and no GUIDs.

**Comment by itadapter** [comment]
Suggested solution:

ApiControllers are cached by app singleton - so they represent a single set of APIs documentation.
So assumption below should work.

An assumption is made that:
- type ids must be stable in the same ApiDoc context
- another ApiDoc context may yield different type id for the same type
- that may change between dll rebuilds

For every type, a stable TYPE ID needs to be generated

1. Use Type.Name first. If such ID is not in the set, then we use that name.
2. If such string is in the set, take LAST segment of namespace and the name.
3. Keep on adding namespace names per step (2)
4. Finally add FQN MD5 + Type's metadata token
or similar... this way we keep it short

[md5(fqn)-]-md5(FullName)-MetadataToken-[instance index]

**Comment by zhabis** [comment]
If the types are to be unique only per specific type set (ApiDocController instance cached via singleton), then why cant we just use auto-incremented type number as in  `0,1,2,3` etc..? If the documentation is produced from the same set of input parameters over the same set of compiled code, we should just be able to increase an integer in the ApiGenerator and use that instead of GUID, why not?

**Comment by itadapter** [comment]
Done. 1.5.7
