### ISSUE TITLE
SlimSerializer serialization binder support

### ISSUE THREAD

**Issue by yallie** [azist/azos#432]
Hello,

BinaryFormatter has a handy feature called serialization binder.
It can be used for versioning of the serialized payloads:

```csharp
private class MySerializationBinder : SerializationBinder
{
	public override Type BindToType(string assemblyName, string typeName)
	{
        // return the requested type from 
	}
}

// used like this:
var formatter = new BinaryFormatter();
formatter.Binder = new MySerializationBinder();
formatter.Deserialize(oldPayload);
```

When deserializing payload created with Library.v1, custom binder can return type from Library.v2.

Does SlimSerializer support anything like this?

Looks like it can be related to TypeSchema, but TypeSchema class is internal.

**Comment by itadapter** [comment]
Alexey,
 SlimSerializer does not support versioning by design, for speed. The point of Slim is to serialize "anything" much faster than BinaryFormatter. 

However, there is Arow serializer which supports versioning, but it only serializes data documents (Azos.Data.Doc).
Arow works faster than SlimSerializer but does not support polymorphism.

The next gen Bix serializer does support polymorphism and even faster than Arow, but it is being developed and not ready yet as of today.

**Comment by yallie** [comment]
Dmitriy, thanks for the explanation!
