### ISSUE TITLE
NotSupportedException: Nullable Structs and SlimSerializer

### ISSUE THREAD

**Issue by topsterde** [azist/azos#481]
Hi,
the attached sample code produces a NotSupportedException.

[SlimSerializerNullableReferenceType.zip](https://github.com/azist/azos/files/6660471/SlimSerializerNullableReferenceType.zip)

Is that the way it is meant to be?

**Comment by zhabis** [comment]
The problem is with broken serialization of `DateTimeOffset` in Core v2+.
Your code works just fine in .Net Framework.
Microsoft broke many classes in CORE  that use `ISerializable/IDeserializationCallback` etc... (e.g. StringComparer.*)

The long term plan is not to use ISerializer-based solution at all, as it is fragile due to lack of MSFT proper support, not
because it is impossible.
Their reasoning is that "binary serialization" is unsafe, which is true for APi use, however it does have many more use-cases (such as in-process cloning etc...)

**Comment by itadapter** [comment]
@topsterde 
If you really need `DateTimeOffset`, you can add it to `SlimReader/Writer` classes so it gets written to stream natively, bypassing broken `ISerializable` implementation

**Comment by topsterde** [comment]
@itadapter In the real application I use many nullable custom structs. I can't add custom structs to SlimReader/Writer.
@zhabis It is very sad :( It is a pity that Microsoft no longer supports this with .net Core v2+.
Many thanks for the support

**Comment by itadapter** [comment]
You can use nullable custom structs just fine.  You do NOT need to add custom structs to SlimRead/Writer.
The problem is with `DateTimeOffset`-specifically as it's internal `ISerializable` implementation changed in Core

**Comment by topsterde** [comment]
@itadapter I can not use nullable custom structs, look at my new attachment :( That's the reason why i created this issue. 
[SlimSerializerNullableReferenceTypeV2.zip](https://github.com/azist/azos/files/6699265/SlimSerializerNullableReferenceTypeV2.zip)
By the way, I also noticed that it doesn't work for some built-in types either e.g. DateTimeOffset.

**Comment by gregorsGit** [comment]
Hi,
I run into the same issue as topsterde.
A simple nullable struct is not working anymore with the Slim-Serializer and .net core.
