### ISSUE TITLE
EventHubServerLogic - protect Route with Idempotency token derived from event.ID

### ISSUE THREAD

**Issue by g8sun** [azist/azos#518]

**Comment by itadapter** [comment]
This is not needed as it it already like this by design:  
a. every Event (raw) has Gdid - they are globally unique
b. an act of writing the already existing Event (a key violation) is treated as SUCCESS without changing any dates or other fields

Therefore, once an event gets in a set per node in a shard -it stays there (until garbage collected much later)
and since GDID is event's PK - the storage tech (such as MongoDB) automatically insures idempotency via key violation)


Thats al

**Comment by itadapter** [comment]
You can now convert EventDoc into Events(raw) and then re-try however you want.

Have added the following extension:
```csharp
public static async Task<WriteResult> PostEventDocumentAsync(this IEventProducer producer,
                                                                 EventDocument evtDoc,
                                                                 JsonDataMap headers = null,
                                                                 DataLossMode? lossMode = null)
    {
      var (attr, partition, rawEvent) = GetRawEventForDocument(producer, evtDoc, headers);
      var result = await producer.PostAsync(attr.Route, partition, rawEvent, lossMode ?? attr.LossMode).ConfigureAwait(false);
      return result;
    }
```
