### ISSUE TITLE
Add support for GET-only fields (Calculated fields) to Schema/FieldDef

### ISSUE THREAD

**Issue by g8sun** [azist/azos#531]
These fields are needed for serialization, because we need to add them to schema as a regular field but their value is calculated

**Comment by itadapter** [comment]
In case a field does not have a setter, then the set() attempt should discard value?
FieldDef does not have a concept of get-only field now. On the other hand it may be acceptable to just discard attempts to write to such field (without putting value in amorphous data even), because Type-safe code would fail as there is no setter, and `SetValue()` should do nothing because "there is nowhere to write".

```csharp
  
  doc.GetOnlyField = 123; //compiler error, can not assign a get-only property
```

This does not affect `DynamicDocs` because this is only driven of `PropertyInfo` which is available only in TypedDocs.

Benefits:
1. Ability to add fields to schema - this is very important for `Info` objects which are read-only
2. Simple natural C# syntax without meaningless empty `set{ }`
3. Natural solution, compiler prevents setting a get-only property statically anyway

Disadvantages:
1. If someone tries to set a field by code, such as `doc.SetField(def, value)` the value gets discarded since, by design the property is get-only.  This behavior is needed so that serializers dont need to check if the typed-doc field is get-only, so they can set field which does not go anywhere
2. Somehow `StoreFlag` needs to be forced to `LoadOnly` for all attributes in such field without a "set()", as the caller should know that this fields can not be "written into"

**Comment by itadapter** [comment]
The change has been implemented.
1. A document field may be delcared as get-only property (without set)
2. FieldDef.GetOnly was added to reflect
3. It participates in schema equality comparison, and documentation as `get-only` flag
4. Attempt to set a `GetOnly` field throws an error `"Can not set get-only field "{0}"`
5. JSON reader bypasses this field and does not put it in amorphous data
