### ISSUE TITLE
Documentation may take incorrect endpoint names during markdown expansion from endpoint section substring

### ISSUE THREAD

**Issue by g8kosh** [azist/azos#569]
### /corporate/hierarchy/version-list/ - `{$title}`
`{$description}`

### /corporate/hierarchy/version/ - `{$title}`
`{$description}`

**Comment by itadapter** [comment]
look like the bug is ApiDocGenerator, not ApiDoc controller, as it generates wrong `doc-content-tpl` as seen in raw data

**Comment by itadapter** [comment]
This is not a bug. By default the system uses Enpoint/$uri attribute as a `DocAnchor`, however in your case you do not have a unique `DocAnchor`, because both URIs share the same prefix. The solution is simple, for your API reformat the markdown to be better structured and rely on set `DocAnchor` properties on every Endpoint. For example:
```
  [ApiEndpointDoc(
   Title="...."
   DocAnchor="### Endpoint X"
)]
```
