### ISSUE TITLE
Add Azos.Data.Business.DataFlow library for programmable questionnaires with invariants/rules, sections conditional forms and scripting 

### ISSUE THREAD

**Issue by g8sun** [azist/azos#606]

**Comment by sergey-msu** [comment]
After talking with you I thought - how will you do the UI layout? Are you going to create your own CSS engine? We had discussed it a few years ago, busness wants to freely move UI components left or right. How will you code this in JSON? It seems to me that this is very difficult task, or I dont understand something.
The question is: is it worth doing this at all. Yes, I also need stuff like this in Pyton, but I still don’t understand how the solution will work relative to the UI

**Comment by zhabis** [comment]
@sergey-msu  there are a few options: 
* Auto flow fields using their tab order set in schema - this may be suitable for many use-cases but not all
* Create a "layout" sub-key in the schema definition for the fieldset, and use some form of a primitive flex-box abstraction with `float: {left, right}` conceptually similar to CSS

The 2nd choice above is the best choice because it would really allow for custom forms.

I have a different question though: why does this need to be in Azos even, since this does not look like a server library?
However these things still need to be provided:

* Schema definition model for the whole flow and its forms, sections and field sets, for every field:
    * Val constraints, value lists etc..
    * Invariants 
* The above serializes into plain JSON
* Need some form of scripting language to declare invariants etc., when the flow gets served in JSON, we can transpile that to ES6 for example

**Comment by zhabis** [comment]
https://esprima.org/demo/parse.html#

```
 $.visible = FirstName.value > 0;
```

produces:

```json
{
  "type": "Program",
  "body": [
    {
      "type": "ExpressionStatement",
      "expression": {
        "type": "AssignmentExpression",
        "operator": "=",
        "left": {
          "type": "MemberExpression",
          "computed": false,
          "object": {
            "type": "Identifier",
            "name": "$"
          },
          "property": {
            "type": "Identifier",
            "name": "visible"
          }
        },
        "right": {
          "type": "BinaryExpression",
          "operator": ">",
          "left": {
            "type": "MemberExpression",
            "computed": false,
            "object": {
              "type": "Identifier",
              "name": "FirstName"
            },
            "property": {
              "type": "Identifier",
              "name": "value"
            }
          },
          "right": {
            "type": "Literal",
            "value": 0,
            "raw": "0"
          }
        }
      }
    }
  ],
  "sourceType": "script"
}
```

**Comment by sergey-msu** [comment]
OK. It will be interesting to see this in action

**Comment by itadapter** [comment]
See ADLIB. DONE differently
